# Generated by Django 6.0.5 on 2026-05-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='asiakas', max_length=50)),
                ('contactname', models.CharField(default='asiakas', max_length=50)),
                ('address', models.CharField(default='asiakas', max_length=100)),
                ('phone', models.CharField(default='asiakas', max_length=20)),
                ('email', models.CharField(default='asiakas', max_length=50)),
                ('country', models.CharField(default='asiakas', max_length=50)),
            ],
        ),
    ]
